""" tools tasks
    """
import importlib
from pyrox.services import log
from controlrox.models.tasks.task import ControllerApplicationTask
from controlrox.models.gui import ladder as ladder_gui


class RoutineTask(ControllerApplicationTask):
    """Routine task for generating and managing PLC routines.
    """

    def debug_draw(self):
        """Debug method to draw the ladder editor frame."""
        log(self).info('Drawing ladder editor frame for debugging...')
        importlib.reload(ladder_gui)
        ladder_frame = ladder_gui.LadderEditorTaskFrame(
            master=self.application.workspace)
        self.application.workspace.add_workspace_task_frame(ladder_frame, raise_frame=True)

    def generate_default_routine(self):
        """Generate a default routine for the PLC application."""
        log(self).info('Generating default routine...')
        if not self.application.controller:
            log(self).error('No controller set in the application.')
            return
        importlib.reload(ladder_gui)
        routine = self.controller.create_routine(name='DefaultRoutine',
                                                 description='Generated by Pyrox Programming Application.')
        ladder_frame = ladder_gui.LadderEditorTaskFrame(
            master=self.application.workspace,
            controller=self.application.controller,
            routine=routine)
        self.application.workspace.add_workspace_task_frame(ladder_frame, raise_frame=True)

    def inject(self) -> None:
        dropdown_menu = self.application.gui_backend.create_gui_menu(
            master=self.application.menu.get_tools_menu().menu,
            name='generate_routine',
            tearoff=0
        )
        dropdown_menu.add_item(
            label='Generate Default Routine',
            command=self.generate_default_routine
        )
        dropdown_menu.add_item(
            label='Draw',
            command=self.debug_draw
        )
        self.application.menu.add_submenu(
            submenu=dropdown_menu,
            label='Generate Routine',
        )
